###
POST http://localhost:3500/login
Content-Type: application/json

{ "email": "mladenj@skydream.info",
  "password":"1234"
}

###
GET http://localhost:3500/admin

###
GET http://localhost:3500/admin/users

###
POST http://localhost:3500/admin/newUser
Content-Type: application/json

{"name":"Jovan",
  "email": "malden@gmail.com",
  "password":"123",
  "emailPassword": "134242",
  "region":"Los Angeles",
  "status":"active"}

###
POST http://localhost:3500/admin/editUser/5d13fa5981a1f8350c74d57e
Content-Type: application/json

{"name":"Jovan",
  "email": "malden@gmail.com",
  "password":"123",
  "emailPassword": "134242",
  "region":"Los Angeles",
  "status":"disabled"}



###
GET http://localhost:3500/admin/rooms/living%20room

###
GET http://localhost:3500/admin/newItem
###

POST http://localhost:3500/admin/items/5d140fc1a1f7e539bcb20893
Content-Type: application/json

###
POST http://localhost:3000/api/admin/user
Content-Type: application/json

{"name":"Roxana",
  "email": "roxana@benleedsproperties.com",
  "password":"123",
  "regionId":"2"}
